---
- name: Instalar pacotes com Chocolatey
  hosts: all
  vars:
    packages:
      - git
      - notepadplusplus
  tasks:
    - name: Instalar pacotes
      community.general.win_chocolatey:
        name: "{{ packages }}"
        state: present
